io:
    savedir: lsst_y1_data/final_runs/importance_sampling/
    cosmology_yaml_file: /home/u7/ssarmabo/cocoa_emulator/cocoa/Cocoa/projects/lsst_y1/template_yamls/mcmc/MCMC_W_BARYONS.yaml
    cocoa_yaml_file: /home/u7/ssarmabo/cocoa_emulator/cocoa/Cocoa/projects/lsst_y1/likelihood/params_cosmo_ia_dz.yaml
    
lhs:
    N_samples: 9600
    
emulator:
    CHI_SQ_CUT: 8e+4
    emu_type: nn
    N_resample: 96000
    batch_size: 16
    n_epochs: 100
    
sampling:
    save_chain: false
    is: 1
    N_MCMC: 40000
    N_BURNIN: 6000
    N_WALKERS: 96
