io:
    savedir: lsst_y1_data/code_run/
    cosmology_yaml_file: /home/u7/ssarmabo/cocoa_emulator/cocoa/Cocoa/projects/lsst_y1/template_yamls/mcmc/MCMC_W_BARYONS.yaml
    cocoa_yaml_file: /home/u7/ssarmabo/cocoa_emulator/cocoa/Cocoa/projects/lsst_y1/likelihood/params_cosmo_ia_dz.yaml
    
lhs:
    N_samples: 480
    
emulator:
    CHI_SQ_CUT: 8e+4
    emu_type: gp
    N_resample: 200
    batch_size: 16
    n_epochs: 100
    
sampling:
    N_MCMC: 2000
    N_BURNIN: 1000
    N_WALKERS: 96