io:
    savedir: output/nn_emu/ 
    #cosmology_yaml_file: /home/u7/ssarmabo/cocoa_emulator/cocoa/Cocoa/projects/lsst_y1/template_yamls/mcmc/MCMC_W_BARYONS.yaml
    cosmology_yaml_file: configs/cocoa_configs/MCMC_W_BARYONS.yaml
    #cocoa_yaml_file: /home/u7/ssarmabo/cocoa_emulator/cocoa/Cocoa/projects/lsst_y1/likelihood/params_cosmo_ia_dz.yaml
    cocoa_yaml_file: configs/cocoa_configs/params_cosmo_ia_dz.yaml
lhs:
    N_samples: 9600
    
emulator:
    CHI_SQ_CUT: 8e+4
    emu_type: nn
    N_resample: 9600
    batch_size: 16
    n_epochs: 100
    
sampling:
    N_MCMC: 1000
    N_BURNIN: 500
    N_WALKERS: 96
